version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
        
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
        
  api:
    image: movieshub:latest
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: ../src/MoviesHub.Api/Dockerfile
    restart: always
    depends_on:
      - redis
      - db
    ports:
      - "5419:80"
      
volumes:
  redis_data:
    driver: local
  db_data:
